POST http://localhost:3008/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###
POST http://localhost:3008/login/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}

###


GET http://localhost:3008/user/tweets/feed/
###

GET http://localhost:3008/user/following/

###

GET http://localhost:3008/user/followers/

###


GET http://localhost:3008/tweets/1022/
###

GET http://localhost:3008/tweets/4025/likes/
###

GET http://localhost:3008/tweets/1/replies/
###

GET http://localhost:3008/user/tweets/